$env:YOLO_CONFIG_DIR = "E:\YOLO\yolo_new\ultralytics_config"

conda activate yolo
Set-Location "E:\YOLO"

# Change this to the best.pt generated by your latest training run.
$Weights = "E:\YOLO\runs\detect\train\weights\best.pt"

yolo export `
  model="$Weights" `
  format=onnx `
  imgsz=320 ` # Change this to the image size you want to use for inference. It should be a multiple of 32.
  opset=12 ` # Change this to the ONNX opset version you want to use. 12 is a good choice for compatibility with most frameworks.
  simplify=True `
  device=cpu
