$env:YOLO_CONFIG_DIR = "E:\YOLO\yolo_new\ultralytics_config"

conda activate yolo
Set-Location "E:\YOLO"

# Change this to the best.pt generated by your latest training run.
$Weights = "E:\YOLO\runs\detect\train\weights\best.pt"

yolo detect predict `
  model="$Weights" `
  source="E:\YOLO\merged\test\images" `
  imgsz=320 `
  conf=0.25 `
  device=0 `
  save=True
