$env:YOLO_CONFIG_DIR = "E:\YOLO\yolo_new\ultralytics_config"

conda activate yolo
Set-Location "E:\YOLO"

# Change this to the last.pt generated by the interrupted training run.
$LastWeights = "E:\YOLO\runs\detect\train\weights\last.pt"

yolo detect train `
  model="$LastWeights" `
  resume=True
