$env:YOLO_CONFIG_DIR = "E:\YOLO\yolo_new\ultralytics_config"

conda activate yolo
Set-Location "E:\YOLO"

# Change this to the best.pt generated by your latest training run.
$Weights = "E:\YOLO\runs\detect\train\weights\best.pt"

yolo detect val `
  model="$Weights" `
  data="E:\YOLO\yolo_new\data.yaml" `
  imgsz=320 `
  split=test `
  device=0
